import type { Metadata } from "next";
import { ThemeProvider } from "@material-tailwind/react";

import "./globals.css";
import Nav from "./NavBar/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
      
        {children}        </body>
    </html>
  );
}
